### PR TITLE
Added a new note to the readme file

### PR DESCRIPTION
**Pull request by konstantine-v**
Just added a line that lets the students know they need to cd into the clones repository. @kevincolten

### CODE REVIEW

**Comment by kevincolten** [comment]
Awesome, but you'll need to pull from upstream to resolve the conflict.

**Comment by kevincolten** [comment]
@MaterialFuture

**Comment by kevincolten** [comment]
Sorry, didn't meant to close it

**Comment by konstantine-v** [comment]
Updated @kevincolten

**Pull request merged**
